### ISSUE TITLE
V detailu konfigurace nejde přejmenovat konfiguraci

### ISSUE THREAD

**Issue by odinuv** [keboola/kbc-ui-doctool-recipes-app#1]
API request se posílá na ex-twitter:
![clipboard01abc](https://cloud.githubusercontent.com/assets/4319320/8853909/57c231c6-315d-11e5-89d3-7870b16ac1aa.png)

**Comment by pivnicek** [comment]
tohle vypada jako to uz funguje, ne?  could not reproduce...

**Comment by pivnicek** [comment]
confirmed.
